version: 0.2

phases:
  build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync . s3://YOUR_BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_ID --paths "/*"
      
artifacts:
  files:
    - '**/*'