version: 0.2

phases:
  build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync . s3://$S3_BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
      
artifacts:
  files:
    - '**/*'